Repository purecloudlabs/opensips, pull requests merged in 2024-01, with the labels that each got.

#51 TELECOM-5187 - Obscure customer data in error logging
  cfg.lex
  cfg.y
  globals.h
  modules/domainpolicy/domainpolicy.c
  modules/sipcapture/sipcapture.c
  modules/tls_openssl/openssl_config.c
  modules/tls_wolfssl/wolfssl_config.c
  modules/tm/ut.h
  modules/usrloc/ul_mod.c
  parser/hf.c
  parser/msg_parser.c
  parser/parse_fline.c
  parser/parse_uri.c
  parser/parse_via.c
  redact_pii.c
  redact_pii.h
Labels: enhancement

#57 TELECOM-9136: Fix HEP reconnect
  modules/proto_hep/proto_hep.c
  net/net_tcp.c
  net/tcp_conn_defs.h
Labels: bug

#58 Sync 3.4
  Makefile.defs
  action.c
  cfg.lex
  cfg.y
  globals.h
  main.c
  mi/mi_core.c
  modules/dialog/README
  modules/dialog/dlg_hash.c
  modules/dialog/doc/contributors.xml
  modules/domainpolicy/domainpolicy.c
  modules/nathelper/README
  modules/nathelper/doc/contributors.xml
  modules/nathelper/doc/nathelper_admin.xml
  modules/presence_dfks/README
  modules/presence_dfks/doc/contributors.xml
  modules/presence_dfks/doc/presence_dfks_admin.xml
  modules/presence_dfks/presence_dfks.h
  modules/proto_hep/proto_hep.c
  modules/rtp_relay/README
  modules/rtp_relay/doc/contributors.xml
  modules/rtp_relay/rtp_relay.c
  modules/rtp_relay/rtp_relay_ctx.c
  modules/sipcapture/sipcapture.c
  modules/tls_openssl/openssl_config.c
  modules/tls_wolfssl/wolfssl_config.c
  modules/tm/ut.h
  modules/tracer/README
  modules/tracer/doc/contributors.xml
  modules/tracer/tracer.c
  modules/usrloc/ul_mod.c
  net/net_tcp.c
  net/tcp_conn_defs.h
  parser/hf.c
  parser/msg_parser.c
  parser/parse_fline.c
  parser/parse_uri.c
  parser/parse_via.c
  pvar.c
  redact_pii.c
  redact_pii.h
  str.h
  transformations.c
Labels: bug, upstream merge

#59 TELECOM-7656: Extend sql_cacher load/reload logs
  modules/sql_cacher/sql_cacher.c
  modules/sql_cacher/sql_cacher.h
Labels: enhancement
